"""Generate the Asterisk configuration that puts the model on the phone line.

Three files are produced:

* ``pjsip.conf``      - a TLS-only transport with SRTP mandatory, one handset
  endpoint (your SIP app), and a commented-out SIP trunk stub for later.
* ``extensions.conf`` - dialplan: the AI extension routes the audio to our
  AudioSocket bridge, plus echo/demo extensions for testing.
* ``rtp.conf``        - the media port window, kept identical to the firewall
  rule so audio cannot be blocked by a rule that disagrees with Asterisk.

Opinionated choices, all of them deliberate:

* ``media_encryption=sdes`` with ``media_encryption_optimistic=no``: encryption
  is mandatory. With ``optimistic=yes`` a client that does not offer SRTP gets a
  plaintext call, which is the exact silent downgrade the rest of this project
  refuses to allow.
* ``direct_media=no``: the model must be in the media path, so Asterisk always
  anchors the RTP. Direct media would bypass the bridge entirely - a
  configuration that "works" and delivers no audio to the model.
* ``dtmf_mode=rfc4733``: in-band DTMF would be transcribed by the ASR and fed to
  the model as digits in the middle of speech.
* No ``identify`` section matching ``0.0.0.0/0``. That is a common paste and it
  identifies *every* source on the internet as your handset. A registering
  endpoint does not need one.
"""

from __future__ import annotations

import os
import secrets
from pathlib import Path

from voice.config import VoiceConfig

HEADER = """\
; {title}
; Generated by `phone voice provision` - edits will be overwritten.
; Regenerate with: phone voice provision --force
;
; TLS is mandatory, SRTP is mandatory, and direct media is off so that the
; assistant stays in the audio path. Do not "fix" any of those three: each one
; either removes encryption or silences the model.
"""

# Asterisk paths for a Debian/Ubuntu install. Kept in one place because a
# wrong ca_list_file produces a transport that silently fails to start.
DEFAULT_CA_BUNDLE = "/etc/ssl/certs/ca-certificates.crt"


def _ca_file(cfg: VoiceConfig) -> str:
    local = cfg.tls_path / "ca-bundle.pem"
    return str(local) if local.is_file() else DEFAULT_CA_BUNDLE


def tls_files(cfg: VoiceConfig) -> tuple[Path, Path]:
    """The certificate and key Asterisk should present.

    Deliberately the same filenames the rest of the project generates
    (`sip/gen-certs.sh`, `phone sip init`), so one `phone sip init` on this host
    produces the credentials for both legs instead of two sets nobody can keep
    straight - and so Asterisk's transport cannot fail to start because it is
    looking for a file that nothing ever wrote.
    """
    return cfg.tls_path / "client.pem", cfg.tls_path / "client.key"


def render_pjsip(cfg: VoiceConfig) -> str:
    cert, key = tls_files(cfg)
    handset_password = cfg.handset_password or "<run phone voice provision to generate>"
    return HEADER.format(title="pjsip.conf - SIP over TLS, SRTP mandatory") + f"""
[global]
type=global

; ---------------------------------------------------------------- transport
; TLS only. There is deliberately no UDP or TCP transport: a single unwanted
; transport is all it takes for signalling to fall back to plaintext.
[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file={cert}
priv_key_file={key}
ca_list_file={_ca_file(cfg)}
method=tlsv1_2

; ------------------------------------------------------------------ handset
; Your SIP app registers here. Media is encrypted and Asterisk anchors the audio.
; There is no `identify` section on purpose: `match=0.0.0.0/0` (a common paste
; from tutorials) would identify every source on the internet as this endpoint,
; and a registered endpoint does not need one.
[{cfg.handset_name}]
type=endpoint
context=from-handset
disallow=all
allow=ulaw,alaw
transport=transport-tls
media_encryption=sdes
media_encryption_optimistic=no
direct_media=no
dtmf_mode=rfc4733
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
ice_support=no
timers=yes
language=en
auth={cfg.handset_name}-auth
aors={cfg.handset_name}
callerid={cfg.handset_name} <{cfg.handset_extension}>

[{cfg.handset_name}-auth]
type=auth
auth_type=userpass
username={cfg.handset_extension}
password={handset_password}

[{cfg.handset_name}]
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=30
maximum_expiration=3600
"""


def render_extensions(cfg: VoiceConfig) -> str:
    owner = cfg.owner_destination.strip()
    owner_digits = "".join(ch for ch in owner if ch.isdigit() or ch == "+")
    pstn_context = _pstn_context(cfg, owner, owner_digits)
    return HEADER.format(title="extensions.conf - dialplan that reaches the model") + f"""
[globals]
BRIDGE_HOST={cfg.host}
BRIDGE_PORT={cfg.port}

; --------------------------------------------------------------- incoming
[from-handset]
; {cfg.ai_extension} - talk to the local model. This is the whole point: the
; channel's audio is handed to our AudioSocket bridge, which does ASR -> LLM ->
; TTS and streams speech back.
exten => {cfg.ai_extension},1,NoOp(AI assistant via AudioSocket)
 same => n,Answer()
 same => n,Set(AUDIOSOCKET_UUID=${{UNIQUEID}})
 same => n,AudioSocket(${{AUDIOSOCKET_UUID}},${{BRIDGE_HOST}},${{BRIDGE_PORT}})
 same => n,Hangup()

; 601 - echo test: proves the audio path (codec, jitter buffer, echo canceller)
; without involving any model. If 601 sounds bad, the model is not the problem.
exten => 601,1,Answer()
 same => n,Playback(hello-world)
 same => n,Echo()
 same => n,Hangup()

; 602 - play a local file, useful for checking levels and codec negotiation.
exten => 602,1,Answer()
 same => n,Playback(demo-congrats)
 same => n,Hangup()

; 603 - report which codec is in use and whether the media is encrypted.
exten => 603,1,Answer()
 same => n,Verbose(1, codec=${{CHANNEL(audionativeformat)}} secure-signalling=${{CHANNEL(secure_bridge_signaling)}} secure-media=${{CHANNEL(secure_bridge_media)}})
 same => n,SayAlpha(${{CHANNEL(audionativeformat)}})
 same => n,Hangup()

; Anything else: refuse, and do not offer an outbound trunk to a compromised
; handset. This is the default-deny posture the firewall also enforces.
exten => _X.,1,Playback(ss-noservice)
 same => n,Hangup()

; -------------------------------------------------------------- behaviour
; Reached only if something explicitly routes here; AudioSocket needs no endpoint.
[ai-internal]
exten => s,1,Hangup()

{_local_context(cfg)}
{pstn_context}"""


def _local_context(cfg: VoiceConfig) -> str:
    return f"""; ------------------------------------------------- outbound: handset
; Reached with `channel originate Local/s@ai-outbound-local ...` if you prefer to
; route the agent's outbound call through the dialplan. `phone voice call --to
; {cfg.handset_extension}` skips this context and attaches AudioSocket to the
; handset leg directly - the same call, one less moving part.
[ai-outbound-local]
exten => s,1,NoOp(agent calls the handset extension)
 same => n,Set(CALLERID(num)={cfg.handset_extension})
 same => n,Dial(PJSIP/{cfg.handset_extension},45)
 same => n,Hangup()
"""


def _pstn_context(cfg: VoiceConfig, owner: str, owner_digits: str) -> str:
    """The dialplan's own allow-list for real telephone numbers.

    The agent's originate path (`phone voice call`) does not go through this
    context at all: `validate_dial_request` in Python refuses every destination
    but the owner before a command is built. This context is the second lock -
    for anyone who routes outbound calls through the dialplan - and it contains
    exactly one permitted destination plus a blanket refusal.
    """
    if owner:
        allowed = f"""; The only number this context will dial, spelled out in full.
exten => {owner_digits},1,NoOp(agent calls the configured owner only)
 same => n,Set(CALLERID(num)={cfg.handset_extension})
 same => n,Dial(PJSIP/{owner_digits}@trunk-provider,45)
 same => n,Hangup()
"""
        note = f"""; owner_destination from voice.conf: {owner}
; Everything else - 911, 411, premium numbers, strangers - hits the refusal
; below. There is no pattern that would let one through.
"""
    else:
        allowed = """; No owner destination is configured, so there is nothing to allow.
"""
        note = """; [dial] owner is unset in voice.conf: outbound dialling is disabled
; completely. Set it, re-run `phone voice provision`, and the single permitted
; destination appears here - literally, not as a pattern.
"""
    return f"""; -------------------------------------------------- outbound: the PSTN
; Only relevant once you have a SIP trunk (see trunk.conf.example). The dialplan
; is a *second* lock: the first is validate_dial_request, which the model cannot
; influence, because the model never sees the number it is allowed to call.
{note}{allowed}exten => _X.,1,NoOp(refusing outbound call to ${{EXTEN}})
 same => n,Playback(ss-noservice)
 same => n,Hangup()
"""


def render_rtp(cfg: VoiceConfig) -> str:
    return HEADER.format(title="rtp.conf - media ports") + f"""
; This window must match the firewall rule exactly. pjsua's default is
; 4000-4010, and this project's firewall defaults to the same range, so all
; three agree by construction rather than by hope.
[general]
rtpstart={cfg.rtp_start}
rtpend={cfg.rtp_end}
strictrtp=yes
icesupport=no
"""


TRUNK_STUB = """\
; ---------------------------------------------------------------------------
; OPTIONAL: a real PSTN number. Not written by `provision` on purpose.
; ---------------------------------------------------------------------------
; Everything above works with no telephone company involved: your SIP app talks
; to Asterisk over TLS, and Asterisk hands the audio to the model. Adding a DID
; provider is what makes the agent reachable from - and able to call - ordinary
; phone numbers.
;
; What that costs, honestly: a US DID is roughly $1-3/month plus $0.005-0.02/min
; for outbound. Trial credit (Telnyx, Flowroute, Twilio) works today and expires,
; and trial accounts usually only call numbers you have verified - fine for
; calling yourself. There is no free PSTN interconnect: someone has to pay the
; carrier that owns the mobile network at the other end. The only genuinely free
; path is a SIP app or ATA on your own LAN dialling extension 600, which is why
; that path is the one the defaults are built for.
;
; Paste this into /etc/asterisk/pjsip.conf and fill in the values:
;
; [trunk-provider]
; type=endpoint
; context=ai-outbound-pstn
; disallow=all
; allow=ulaw,alaw
; outbound_auth=trunk-auth
; aors=trunk
; from_user=<your account>
; from_domain=<provider host>
; transport=transport-tls
; media_encryption=sdes
; media_encryption_optimistic=no
; direct_media=no
; rtp_symmetric=yes
; force_rport=yes
; rewrite_contact=yes
;
; [trunk-auth]
; type=auth
; auth_type=userpass
; username=<your account>
; password=<your password>
;
; [trunk]
; type=aor
; contact=sip:<provider host>:5061
; qualify_frequency=30
;
; [trunk-identify]
; type=identify
; endpoint=trunk-provider
; match=<provider signalling IP>       ; from the provider's docs - a hostname here
;                                      ; will not work; resolve it once and pin it
;
; Then tell Asterisk that a real number is allowed to ring the agent. In
; extensions.conf, add an inbound context and point the trunk's `context=` at it:
;
; [from-trunk]
; exten => <your DID>,1,NoOp(inbound call for the agent)
;  same => n,Answer()
;  same => n,AudioSocket(${UNIQUEID},${BRIDGE_HOST},${BRIDGE_PORT})
;  same => n,Hangup()
; exten => _X.,1,Hangup()
;
; Two warnings before you do this:
;   1. A trunk means the dialplan can reach the whole PSTN. Keep the model out of
;      the dial string (validate_dial_request already does) and keep 911
;      unreachable from anything automated: an AI voice cannot give CPR
;      instructions it is not trained for, and a misdial is not recoverable.
;   2. Calling *other people* with an AI voice is regulated. The FCC treats
;      AI-generated voices as "artificial" under the TCPA, so consent and
;      disclosure rules apply, as does your provider's AUP and STIR/SHAKEN.
;      Pennsylvania is an all-party consent state for recording. Calling
;      yourself is not a problem; dialling strangers is.
"""


FILES = {
    "pjsip.conf": render_pjsip,
    "extensions.conf": render_extensions,
    "rtp.conf": render_rtp,
}


def provision(cfg: VoiceConfig, directory: str, *, force: bool = False) -> list[Path]:
    """Write the Asterisk files. Returns the paths written."""
    target = Path(os.path.expanduser(directory))
    target.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, renderer in FILES.items():
        path = target / name
        if path.exists() and not force:
            raise FileExistsError(
                f"{path} already exists (use --force to back it up and replace; "
                "Asterisk is unlikely to enjoy losing an unrelated config)"
            )
        if path.exists():
            path.replace(path.with_suffix(path.suffix + f".bak.{secrets.token_hex(4)}"))
        path.write_text(renderer(cfg), encoding="utf-8")
        written.append(path)
    return written


def write_trunk_stub(directory: str) -> Path:
    target = Path(os.path.expanduser(directory))
    target.mkdir(parents=True, exist_ok=True)
    path = target / "trunk.conf.example"
    path.write_text(TRUNK_STUB, encoding="utf-8")
    return path


def render_trunk_stub() -> str:
    """Kept for tests and for `phone voice provision --print-trunk`."""
    return TRUNK_STUB
